# Generated by Django 4.2.1 on 2023-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('visits', models.IntegerField(default=0)),
                ('birthday', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
