# Generated by Django 4.2.1 on 2023-05-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_remove_list_user_folder_list_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='parent_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lists.folder'),
        ),
    ]
